spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:postgresql://localhost:5432/mybatis_learn
          username: postgres
          password:
          driver-class-name: org.postgresql.Driver
        slave:
          url: jdbc:postgresql://localhost:5432/mybatis_learn_slave
          username: postgres
          password:
          driver-class-name: org.postgresql.Driver

